// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: dlmsprocessor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOBISRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meter         []*Meter               `protobuf:"bytes,1,rep,name=meter,proto3" json:"meter,omitempty"`
	Obis          string                 `protobuf:"bytes,2,opt,name=obis,proto3" json:"obis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOBISRequest) Reset() {
	*x = GetOBISRequest{}
	mi := &file_dlmsprocessor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOBISRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOBISRequest) ProtoMessage() {}

func (x *GetOBISRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dlmsprocessor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOBISRequest.ProtoReflect.Descriptor instead.
func (*GetOBISRequest) Descriptor() ([]byte, []int) {
	return file_dlmsprocessor_proto_rawDescGZIP(), []int{0}
}

func (x *GetOBISRequest) GetMeter() []*Meter {
	if x != nil {
		return x.Meter
	}
	return nil
}

func (x *GetOBISRequest) GetObis() string {
	if x != nil {
		return x.Obis
	}
	return ""
}

type Meter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Obis          string                 `protobuf:"bytes,3,opt,name=obis,proto3" json:"obis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meter) Reset() {
	*x = Meter{}
	mi := &file_dlmsprocessor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meter) ProtoMessage() {}

func (x *Meter) ProtoReflect() protoreflect.Message {
	mi := &file_dlmsprocessor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meter.ProtoReflect.Descriptor instead.
func (*Meter) Descriptor() ([]byte, []int) {
	return file_dlmsprocessor_proto_rawDescGZIP(), []int{1}
}

func (x *Meter) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Meter) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Meter) GetObis() string {
	if x != nil {
		return x.Obis
	}
	return ""
}

type GetOBISResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOBISResponse) Reset() {
	*x = GetOBISResponse{}
	mi := &file_dlmsprocessor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOBISResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOBISResponse) ProtoMessage() {}

func (x *GetOBISResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dlmsprocessor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOBISResponse.ProtoReflect.Descriptor instead.
func (*GetOBISResponse) Descriptor() ([]byte, []int) {
	return file_dlmsprocessor_proto_rawDescGZIP(), []int{2}
}

func (x *GetOBISResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_dlmsprocessor_proto protoreflect.FileDescriptor

const file_dlmsprocessor_proto_rawDesc = "" +
	"\n" +
	"\x13dlmsprocessor.proto\x12\rdlmsprocessor\"P\n" +
	"\x0eGetOBISRequest\x12*\n" +
	"\x05meter\x18\x01 \x03(\v2\x14.dlmsprocessor.MeterR\x05meter\x12\x12\n" +
	"\x04obis\x18\x02 \x01(\tR\x04obis\"?\n" +
	"\x05Meter\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04obis\x18\x03 \x01(\tR\x04obis\"'\n" +
	"\x0fGetOBISResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2[\n" +
	"\rDLMSProcessor\x12J\n" +
	"\aGetOBIS\x12\x1d.dlmsprocessor.GetOBISRequest\x1a\x1e.dlmsprocessor.GetOBISResponse0\x01B\x15Z\x13dlmsprocessor/protob\x06proto3"

var (
	file_dlmsprocessor_proto_rawDescOnce sync.Once
	file_dlmsprocessor_proto_rawDescData []byte
)

func file_dlmsprocessor_proto_rawDescGZIP() []byte {
	file_dlmsprocessor_proto_rawDescOnce.Do(func() {
		file_dlmsprocessor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dlmsprocessor_proto_rawDesc), len(file_dlmsprocessor_proto_rawDesc)))
	})
	return file_dlmsprocessor_proto_rawDescData
}

var file_dlmsprocessor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dlmsprocessor_proto_goTypes = []any{
	(*GetOBISRequest)(nil),  // 0: dlmsprocessor.GetOBISRequest
	(*Meter)(nil),           // 1: dlmsprocessor.Meter
	(*GetOBISResponse)(nil), // 2: dlmsprocessor.GetOBISResponse
}
var file_dlmsprocessor_proto_depIdxs = []int32{
	1, // 0: dlmsprocessor.GetOBISRequest.meter:type_name -> dlmsprocessor.Meter
	0, // 1: dlmsprocessor.DLMSProcessor.GetOBIS:input_type -> dlmsprocessor.GetOBISRequest
	2, // 2: dlmsprocessor.DLMSProcessor.GetOBIS:output_type -> dlmsprocessor.GetOBISResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dlmsprocessor_proto_init() }
func file_dlmsprocessor_proto_init() {
	if File_dlmsprocessor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dlmsprocessor_proto_rawDesc), len(file_dlmsprocessor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dlmsprocessor_proto_goTypes,
		DependencyIndexes: file_dlmsprocessor_proto_depIdxs,
		MessageInfos:      file_dlmsprocessor_proto_msgTypes,
	}.Build()
	File_dlmsprocessor_proto = out.File
	file_dlmsprocessor_proto_goTypes = nil
	file_dlmsprocessor_proto_depIdxs = nil
}
